# why debug...
# 1) pro is not running and causing unexpected errors...
# 2) pro is working finne but not working the same way we want...
# python debugger.........
import pdb 

age = input("enter your age : ")
pdb.set_trace()
age = age + 5
print(f"your age is {age} after 5 years")